name: Java FX

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '26'
          check-latest: true
          cache: 'gradle'
      - name: Lint
        run: bash ./gradlew lintDebug --stacktrace --no-configuration-cache

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '26'
          check-latest: true
          cache: 'gradle'
      - name: Unit tests
        run: bash ./gradlew test --stacktrace --no-configuration-cache

  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Set up GraalVM
        uses: actions/setup-java@v5
        with:
          distribution: graalvm
          java-version: '26'
          check-latest: true
          cache: gradle
      - name: Verify GraalVM
        run: |
          java --version
          native-image --version
      - name: Build debug APK
        run: bash ./gradlew nativeCompile --no-configuration-cache
      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: app-dev-debug
          path: app/javafx/build/native/nativeCompile/deck-pc
