name: Build

on:
  push:

jobs:
  domain:
    name: Lib
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 26

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic
          cache-read-only: false

      - name: Build Lib
        run: ./gradlew :domain:usecases:build

  e2e:
    runs-on: ubuntu-latest
    name: Lib E2E
    needs: domain
    strategy:
      fail-fast: false
      matrix:
        nextcloud-version: [ 'nextcloud:latest', 'nextcloud:stable', 'nextcloud:production' ]
    env:
      NEXTCLOUD_ADMIN_USER: Test
      NEXTCLOUD_ADMIN_PASSWORD: Test
      NEXTCLOUD_TRUSTED_DOMAINS: localhost
    services:
      nextcloud:
        image: ${{ matrix.nextcloud-version }}
        env:
          SQLITE_DATABASE: db.sqlite
          NEXTCLOUD_ADMIN_USER: ${{ env.NEXTCLOUD_ADMIN_USER }}
          NEXTCLOUD_ADMIN_PASSWORD: ${{ env.NEXTCLOUD_ADMIN_PASSWORD }}
          NEXTCLOUD_TRUSTED_DOMAINS: ${{ env.NEXTCLOUD_TRUSTED_DOMAINS }}
        ports:
          - 80:80
        options: >-
          --health-cmd "curl GET 'http://Test:Test@localhost/ocs/v2.php/apps/serverinfo/api/v1/info' -f -H 'OCS-APIRequest: true' || exit 1"
          --health-interval 1s
          --health-timeout 2s
          --health-retries 10
          --health-start-period 3s
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Enable Deck app
        run: |
          docker exec $(docker ps -f "name=nextcloud" -q) bash -c 'runuser -u www-data -- php occ app:install deck'

      - name: Verify Nextcloud setup
        run: |
          curl -v -X GET "http://$NEXTCLOUD_ADMIN_USER:$NEXTCLOUD_ADMIN_PASSWORD@$NEXTCLOUD_TRUSTED_DOMAINS:$NEXTCLOUD_PORT/ocs/v2.php/cloud/capabilities?format=json" -H 'OCS-APIRequest: true' | jq

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 26

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic
          cache-read-only: false

      - name: Run E2E
        run: ./gradlew :domain:usecases:test -PincludeE2E=true --stacktrace

      - name: Upload Reports
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: domain-e2e-report
          path: |
            **/build/reports/tests/test/**
            ${{ runner.temp }}/.gradle-actions/build-results/*.json

  javafx:
    name: App (PC)
    runs-on: ubuntu-latest
    needs: domain

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 26

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic
          cache-read-only: false

      - name: Build App
        run: ./gradlew :app:javafx:shadowJar

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: jar
          path: app/javafx/build/libs/*all.jar

  android:
    name: App (Android)
    runs-on: ubuntu-latest
    needs: domain

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 26

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic
          cache-read-only: false

      - name: Build App
        run: ./gradlew :app:android:build

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: apk
          path: app/android/build/outputs/apk/debug/android-debug.apk

  cli:
    name: App (CLI)
    runs-on: ubuntu-latest
    needs: domain

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 26

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic
          cache-read-only: false

      - name: Build App
        run: ./gradlew :app:cli:build

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: cli
          path: app/cli/build/libs/cli-all.jar
